development:
  secret_key_base: cb874357ceef54e600faa840a73354486d4d302aac1ffe3d7974f186bed29a1f29e5dabd10c1b0704835779c1a7d6e29491681ff8b014c8526035b2ad2e197b9
  s3_storage:
    access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] || "" %>
    secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] || "" %>
test:
  secret_key_base: aabb7e5e19c640a94ffd75312abc43868dc97096ca22b86af575967fe4ce54ff4021d7c3a7bcfd70dc62197e10391bd8f556b2d6d1dd6faf92703b6b4e8c946c
  s3_storage:
    access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] || "" %>
    secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] || "" %>

staging_and_production: &defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_storage:
    access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] || "" %>
    secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] || "" %>
  mailer:
    address: <%= ENV["MAILER_ADDRESS_KEY"] || "" %>
    port: <%= ENV["MAILER_PORT_KEY"] || "" %>
    domain: <%= ENV["MAILER_DOMAIN_KEY"] || "" %>
    username: <%= ENV["MAILER_USERNAME_KEY"] || "" %>
    password: <%= ENV["MAILER_PASSWORD_KEY"] || "" %>
    asset_host: <%= ENV["MAILER_ASSET_HOST_KEY"] || "" %>
    host: <%= ENV["MAILER_HOST_KEY"] || "" %>

production:
  <<: *defaults

staging:
  <<: *defaults
